apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: zabbix
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: zabbix
